name: second-workflow 
on : [push]
jobs:check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          python --version
          pipenv --python 3.9
          pipenv install nose pylint --dev
          pipenv run pylint "app/tests/test_example.py"

          
